<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
//use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class FakeCustomerManualSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // No factories YET, I just need it to test the DB working at all and maybe have some
        // primitive blades before the full ORM Model-View-Controller is done
        // So I am doing it for ONE table only -- Clients -- because there are no foreign keys here
        // and in an external seeder to be run MANUALLY
        DB::table('customers')->insert([
            'full_name'=>Str::random(10),
            'email_address'=>Str::random(6).'.'.Str::random(3).'.com',
            'phone_number'=>'+380'.mt_rand(10000000,999999999), // hope implicit conversion works out?
            'comment'=>'Dummy customer generated by Fake Customer Manual Seeder'
        ]);
    }
}
