<?php

namespace Database\Factories;

use App\Models\Company;
use App\Models\Customer;
use Illuminate\Database\Eloquent\Factories\Factory;
#use Illuminate\Support\Facades\DB; #unused now as I switched to appropriate ORM
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Model>
 */
class CustomerFactory extends Factory
{
    //SHOULD ADD corresponding model name here, and it will be not FakeCustomer but Customer!
    //FIXME add correct model name... when I implement the model Customer itself

    /**
     *
     * The name of the factory's corresponding model.
     *
     * @var string
     */
#    protected $model = User::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
                'full_name'=>fake()->name,
                'email_address'=>fake()->unique()->safeEmail,
                'phone_number'=>'+380'.mt_rand(10000000,999999999), // hope implicit conversion works out?
                'company_id'=>Company::inRandomOrder()->first(), // присвоюємо рандомну компанію, теж непогано б перевіряти, чи їх >0, або помилку видавати
                'comment'=>'Dummy customer generated by Fake Customer Factory v 2.0, with human-like names and email'
            ];
    }
}
