<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
#use Illuminate\Support\Facades\DB; #unused now as I switched to appropriate ORM
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Model>
 */
class CustomerFactory extends Factory
{
    //SHOULD ADD corresponding model name here, and it will be not FakeCustomer but Customer!
    //FIXME add correct model name... when I implement the model Customer itself

    /**
     *
     * The name of the factory's corresponding model.
     *
     * @var string
     */
#    protected $model = User::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
                'full_name'=>Str::random(10),
                'email_address'=>Str::random(6).'.'.Str::random(3).'.com',
                'phone_number'=>'+380'.mt_rand(10000000,999999999), // hope implicit conversion works out?
                'comment'=>'Dummy customer generated by Fake Customer Factory'
            ];
    }
}
